// Pricing plans configuration
export const pricingPlans = [
  {
    name: "Free",
    price: "$0",
    period: "forever",
    description: "Perfect for trying out RoomAI",
    features: [
      "5 design generations per month",
      "3 design styles",
      "Standard quality output",
      "Community support",
    ],
    limitations: ["No commercial use", "Watermarked outputs"],
    cta: "Get Started",
    popular: false,
  },
  {
    name: "Pro",
    price: "$29",
    period: "per month",
    description: "For serious home designers",
    features: [
      "100 design generations per month",
      "All design styles",
      "HD quality output",
      "Priority support",
      "Commercial use license",
      "No watermarks",
      "Download in PNG & JPG",
    ],
    limitations: [],
    cta: "Start Free Trial",
    popular: true,
  },
  {
    name: "Enterprise",
    price: "$99",
    period: "per month",
    description: "For teams and agencies",
    features: [
      "Unlimited generations",
      "All design styles + custom styles",
      "4K quality output",
      "Dedicated support",
      "API access",
      "Team collaboration",
      "White-label options",
      "Advanced analytics",
    ],
    limitations: [],
    cta: "Contact Sales",
    popular: false,
  },
];

// Admin mock data for development
export const mockAdminUsers = [
  {
    id: "admin-user-1",
    name: "John Smith",
    email: "john@example.com",
    plan: "pro",
    credits: 85,
    designs: 12,
    joinedAt: "2023-11-15",
    status: "active",
  },
  {
    id: "admin-user-2",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    plan: "enterprise",
    credits: 450,
    designs: 34,
    joinedAt: "2023-10-20",
    status: "active",
  },
  {
    id: "admin-user-3",
    name: "Mike Chen",
    email: "mike@example.com",
    plan: "free",
    credits: 3,
    designs: 2,
    joinedAt: "2024-01-10",
    status: "active",
  },
];
